/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mila (Liudmyla) Andrushchenko (https://sketchfab.com/mila3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glowing-flower-f25f5af218694950a1b9a0452046caea
Title: Glowing Flower
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Flower(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/glowing_flower.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="44628ce14fd049dba2e607fb373cdc08fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Plane" rotation={[-1.687, 0.097, -0.032]} scale={100}>
                  <mesh
                    name="Plane_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Plane_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group
                  name="Plane001"
                  position={[0, -20.512, 0]}
                  rotation={[-1.671, 0.019, -0.33]}
                  scale={148.893}>
                  <mesh
                    name="Plane001_Material003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane001_Material003_0.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Plane002"
                  position={[0, -29.162, 0]}
                  rotation={[-1.869, -0.197, 0.618]}
                  scale={[101.647, 101.647, 190.174]}>
                  <mesh
                    name="Plane002_Material002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group name="Plane003" rotation={[-1.477, 0.038, -0.984]} scale={100}>
                  <mesh
                    name="Plane003_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Plane003_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group name="Plane004" rotation={[-1.661, -0.115, -2.244]} scale={100}>
                  <mesh
                    name="Plane004_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane004_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Plane004_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane004_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group name="Plane005" rotation={[-1.469, -0.171, 3.12]} scale={100}>
                  <mesh
                    name="Plane005_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane005_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Plane005_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane005_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group name="Plane006" rotation={[-1.627, -0.12, 2.155]} scale={100}>
                  <mesh
                    name="Plane006_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane006_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Plane006_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane006_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group name="Plane007" rotation={[-1.491, 0.094, 0.994]} scale={100}>
                  <mesh
                    name="Plane007_Material004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane007_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Plane007_Material005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane007_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group
                  name="Plane008"
                  position={[0, -20.512, 0]}
                  rotation={[-1.522, -0.116, -2.62]}
                  scale={148.893}>
                  <mesh
                    name="Plane008_Material003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane008_Material003_0.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Plane009"
                  position={[0, -20.512, 0]}
                  rotation={[-1.481, -0.161, 1.434]}
                  scale={148.893}>
                  <mesh
                    name="Plane009_Material003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane009_Material003_0.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Plane010"
                  position={[0, -29.162, 0]}
                  rotation={[-1.658, 0.299, -1.439]}
                  scale={[101.647, 101.647, 190.174]}>
                  <mesh
                    name="Plane010_Material002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane010_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Plane011"
                  position={[0, -29.162, 0]}
                  rotation={[-1.365, -0.296, 2.185]}
                  scale={[101.647, 101.647, 190.174]}>
                  <mesh
                    name="Plane011_Material002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane011_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group name="Vert001" rotation={[-1.622, -0.078, -2.98]} scale={100}>
                  <mesh
                    name="Vert001_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Vert001_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Vert002" rotation={[-1.664, -0.041, -0.023]} scale={100}>
                  <mesh
                    name="Vert002_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Vert002_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Vert003" rotation={[-1.541, 0.058, -2.985]} scale={100}>
                  <mesh
                    name="Vert003_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Vert003_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Point" position={[0, 60.563, 0]} scale={100}>
                  <group name="Object_41" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_42" />
                  </group>
                </group>
                <group name="Point001" position={[-153.344, 59.915, -93.066]} scale={100}>
                  <group name="Object_44" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_45" />
                  </group>
                </group>
                <group name="Point002" position={[91.825, 69.932, 84.926]} scale={100}>
                  <group name="Object_47" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_48" />
                  </group>
                </group>
                <group name="Empty" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Empty001" position={[9.321, 0, 0]} />
                  <group
                    name="Sphere003"
                    position={[0.671, -0.648, 3.301]}
                    rotation={[0, 0, -1.895]}
                    scale={1.422}>
                    <mesh
                      name="Sphere003_Material007_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere003_Material007_0.geometry}
                      material={materials['Material.007']}
                    />
                  </group>
                </group>
                <group name="Point003" position={[-111.03, 187.882, -156.494]} scale={100}>
                  <group name="Object_54" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_55" />
                  </group>
                </group>
                <group name="Point004" position={[177.068, 177.235, -35.62]} scale={100}>
                  <group name="Object_57" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_58" />
                  </group>
                </group>
                <group name="Point005" position={[-153.893, 169.559, 92.549]} scale={100}>
                  <group name="Object_60" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_61" />
                  </group>
                </group>
                <group
                  name="Circle"
                  position={[0, -31.155, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="Circle_Material_007_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_Material_007_0.geometry}
                    material={materials.Material_007}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/glowing_flower.glb')
